### ISSUE TITLE
Add missing non balanced objects (word, paragraph, sentence…)

### ISSUE THREAD

**Issue by Delapouite** [alexherbo2/split-object.kak#1]
Hi Alex.

Thanks for this great script, very useful as usual!

Currently it only supports "balanced objects" like parens and brackets.
Do you plan to add missing ones like `w` (word) `p` (paragraph)… ? I haven't looked at the code yet but I guess it would require a different strategy to select them.

**Comment by alexherbo2** [comment]
Oups

**Comment by alexherbo2** [comment]
I was on my phone and misclicked.
