### ISSUE TITLE
Provide the "real split" feature

### ISSUE THREAD

**Issue by Delapouite** [alexherbo2/split-object.kak#2]
Hello

Natively, Kakoune has 2 opposite commands: `s` to select and `S` to split.

What this plugins offers is more related to the `s` command. It is really useful by itself by I think the `S` counterpart would also be a nice addition in some situation.

Currently the plugin is able to select `foo` and `bar` if `blabla (foo) and (bar) blabla` if we split by parenthesis. The opposite would be to select `blabla(` `) and (` and `) blabla`.

I reckon this may be achieved with something like first saving the current selection `Z`, doing the split and then doing a `<a-z>i` (intersection) or something like that.

In this scenario, a bit of renaming would be necessary. The current function would be renamed 'select' and the new one would be 'split'.

**Comment by alexherbo2** [comment]
I have to rename the plug-in?

**Comment by alexherbo2** [comment]
I cannot reproduce split with `Z<a-I>b<a-z>i`.

Intersection is not that, but it could be interesting to support a split `s` operator.

**Comment by Delapouite** [comment]
Yes a `d` operator or similar may be needed. I think `vis` already has similar a operation missing from Kakoune: https://github.com/martanne/vis/wiki/Differences-from-Kakoune . I'll have to try the `subtract` or `complement` thing to see what it does.

**Comment by alexherbo2** [comment]
In the end, the new split will just be a derivation of the current split.

**Comment by alexherbo2** [comment]
I have a plan of a diff using marks, but it might be better to be a plug-in on its own.

What do you think of it?
